### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [tmbtech/CodePathTodoApp#1]
Hello Robbie,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo). With regards to extensions to implement, we are looking for developers with an interest in user experience and product development so be sure to focus on additional functional enhancements and/or improving the user interface of the app. You can [re-submit on the application dashboard anytime](https://apply.codepath.com/dashboard/) and we'll take another look.

We'll be following up with you again shortly to outline the next steps in the admissions process.

**Comment by nesquena** [comment]
Hi Robbie,

Now that you've submitted an initial pre-work, the next step is to continue working on extensions to your todo app and to [schedule a short 15-minute phone conversation with us here](https://calendly.com/codepath/android-conversations). Find a date that works for you and confirm a 15-minute slot. Let us know if none of those times work. You can [read more about how to prepare for the phone conversation here](https://courses.codepath.com/snippets/intro_to_android/phone_conversation). 

Prior to our chat, can you take some time to research the most common Android Activity lifecycle methods as well as the `ArrayAdapter` pattern used when working with lists? We will be discussing these topics with you conceptually in the phone call. We encourage you to [search our guides](http://guides.codepath.com/android/) as well as any other sources you'd like. 

Once you [select a slot](https://calendly.com/codepath/android-conversations), you'll be sent a calendar invite with the phone number to call. Look forward to chatting soon!
